version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:11.7.0
    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "2b:e8:66:31:b5:2a:d2:bc:41:33:ab:54:59:01:39:ca"
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      # run deploy!
      - deploy:
          name: Deploy
          command: yarn deploy
